import { Component, OnInit } from '@angular/core';
import { AfterViewInit, ViewChild } from '@angular/core';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
export interface PeriodicElement {
  name: string;
  logo: string;
  Rank: number;
  Point: number;
  Match: number;
  Win: number;
  Draw: number;
  Lose: number;
  GF: number;
  GA: number;
  GD: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
  {
    Rank: 1,
    logo: 'vi/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
    name: '	Liverpool',
    Match:14,
    Point: 31,
    Win: 9,
    Draw: 4,
    Lose: 1,
    GF: 36,
    GA: 19,
    GD: '+17',

  },
  {
    Rank: 2,
    logo: 'commons/f/f3/Leicester_City_FC_PL.png',
    name: 'Leicester',
    Point: 27,
    Win: 9,
    Draw: 0,
    Lose: 5,
    GF: 26,
    GA: 17,
    GD: '+9',
    Match:14,
  },
  {
    Rank: 3,
    logo: 'vi/thumb/a/a1/Man_Utd_FC_.svg/1200px-Man_Utd_FC_.svg.png',
    name: 'Man Utd',
    Point: 26,
    Win: 8,
    Draw: 2,
    Lose: 3,
    GF: 28,
    GA: 21,
    GD: '+7',
    Match:13,
  },
  {
    Rank: 4,
    logo: 'vi/7/7c/Everton_FC_logo.svg',
    name: 'Everton',
    Point: 26,
    Win: 8,
    Draw: 2,
    Lose: 4,
    GF: 25,
    GA: 19,
    GD: '+6',
    Match:14,
  },
  {
    Rank: 5,
    logo: 'vi/thumb/5/5c/Chelsea_crest.svg/1200px-Chelsea_crest.svg.png',
    name: 'Chelsea',
    Point: 25,
    Win: 7,
    Draw: 4,
    Lose: 3,
    GF: 29,
    GA: 14,
    GD: '+15',
    Match:14,
  },
  {
    Rank: 6,
    logo: 'vi/8/81/Tottenham_Hotspur_FC.png',
    name: 'Tottenham',
    Point: 25,
    Win: 7,
    Draw: 4,
    Lose: 3,
    GF: 25,
    GA: 14,
    GD: '+11',
    Match:14,
  },
  {
    Rank: 7,
    logo: 'vi/thumb/4/4b/356px-FC_Southampton.svg.png/200px-356px-FC_Southampton.svg.png',
    name: 'Southampton',
    Point: 24,
    Win: 7,
    Draw: 3,
    Lose: 4,
    GF: 25,
    GA: 19,
    GD: '+6',
    Match:14,
  },
  {
    Rank: 8,
    logo: 'vi/1/1d/Manchester_City_FC_logo.svg',
    name: 'Man City',
    Point: 23,
    Win: 6,
    Draw: 5,
    Lose: 2,
    GF: 19,
    GA: 12,
    GD: '+7',
    Match:13,
  },
  {
    Rank: 9,
    logo: 'vi/0/0d/Aston_Villa_FC.png',
    name: '	Aston Villa',
    Point: 22,
    Win: 7,
    Draw: 1,
    Lose: 4,
    GF: 24,
    GA: 13,
    GD: '+11',
    Match:12,
  },
  {
    Rank: 10,
    logo: 'vi/b/b1/WestHam.png',
    name: 'West Ham',
    Point: 21,
    Win: 6,
    Draw: 3,
    Lose: 5,
    GF: 21,
    GA: 19,
    GD: '+2',
    Match:14,
  },
  {
    Rank: 11,
    logo: 'vi/6/6c/Wolverhampton_Wanderers.png',
    name: 'Wolverhampton',
    Point: 20,
    Win: 6,
    Draw: 2,
    Lose: 6,
    GF: 14,
    GA: 19,
    GD: '-5',
    Match:14,
  },
  {
    Rank: 12,
    logo: 'vi/0/0d/Newcastle_United_FC.png',
    name: '	Newcastle',
    Point: 18,
    Win: 5,
    Draw: 3,
    Lose: 5,
    GF: 17,
    GA: 22,
    GD: '-5',
    Match:13,
  },
  {
    Rank: 13,
    logo: 'en/thumb/0/0c/Crystal_Palace_FC_logo.svg/1200px-Crystal_Palace_FC_logo.svg.png',
    name: '	Crystal Palace',
    Point: 18,
    Win: 5,
    Draw: 3,
    Lose: 6,
    GF: 19,
    GA: 25,
    GD: '-6',
    Match:14,
  },
  {
    Rank: 14,
    logo: 'en/thumb/5/54/Leeds_United_F.C._logo.svg/1200px-Leeds_United_F.C._logo.svg.png',
    name: '	Leeds',
    Point: 17,
    Win: 5,
    Draw: 2,
    Lose: 7,
    GF: 24,
    GA: 30,
    GD: '-6',
    Match:14,
  },
  {
    Rank: 15,
    logo: 'vi/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png',
    name: 'Arsenal',
    Point: 15,
    Win: 4,
    Draw: 2,
    Lose: 8,
    GF: 12,
    GA: 18,
    GD: '-6',
    Match:14,
  },
  {
    Rank: 16,
    logo: 'vi/1/1a/Burnley_FC.png',
    name: 'Burnley',
    Point: 13,
    Win: 3,
    Draw: 4,
    Lose: 6,
    GF: 8,
    GA: 19,
    GD: '-11',
    Match:13,
  },
  {
    Rank: 17,
    logo: 'vi/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1200px-Brighton_%26_Hove_Albion_logo.svg.png',
    name: '	Brighton',
    Point: 12,
    Win: 2,
    Draw: 6,
    Lose: 6,
    GF: 16,
    GA: 22,
    GD: '-6',
    Match:14,
  },
  {
    Rank: 18,
    logo: 'vi/8/8d/Fulham_FC.png',
    name: '	Fulham',
    Point: 10,
    Win: 2,
    Draw: 4,
    Lose: 8,
    GF: 13,
    GA: 23,
    GD: '-10',
    Match:14,
  },
  {
    Rank: 19,
    logo: 'vi/b/b1/West_Bromwich_Albion.png',
    name: 'West Bromwich',
    Point: 7,
    Win: 1,
    Draw: 4,
    Lose: 9,
    GF: 10,
    GA: 29,
    GD: '-19',
    Match:14,
  },
  {
    Rank: 20,
    logo: 'vi/thumb/c/c9/Bladeslogo2.png/175px-Bladeslogo2.png',
    name: '	Sheff Utd',
    Point: 2,
    Win: 0,
    Draw: 2,
    Lose: 12,
    GF: 8,
    GA: 25,
    GD: '-17',
    Match:14,
  },
];
@Component({
  selector: 'app-rank',
  templateUrl: './rank.component.html',
  styleUrls: ['./rank.component.css'],
})
export class RankComponent implements OnInit {
  active = 'top';
  constructor() {}

  ngOnInit(): void {}
  displayedColumns: string[] = [
    'Rank',
    'name',
    'Match',
    'Win',
    'Draw',
    'Lose',
    'GF',
    'GA',
    'GD',
    'Point',
  ];
  dataSource = new MatTableDataSource(ELEMENT_DATA);

  @ViewChild(MatSort) sort: MatSort;

  ngAfterViewInit() {
    this.dataSource.sort = this.sort;
  }
}
export class NzDemoLayoutFixedSiderComponent {}
